/** UI chrome strings (zh-TW is the source language; see the app's i18n plan). */
export const t = {
  siteName: 'KK Trip 旅誌',
  siteTagline: '旅行靈感、目的地指南與 KK Trip 的最新消息。',
  home: '首頁',
  allPosts: '所有文章',
  news: '新聞',
  latest: '最新文章',
  topics: '主題',
  readMin: (n: number) => `${n} 分鐘閱讀`,
  by: (name: string) => `By ${name}`,
  backToAll: '返回所有文章',
  postsTagged: (tag: string) => `主題：${tag}`,
  noPosts: '還沒有發佈的文章，敬請期待。',
  loadError: '暫時無法載入文章，請稍後再試。',
  notFound: '找不到這個頁面',
  notFoundBody: '這篇文章可能已被移除，或網址有誤。',
  openApp: '開啟 KK Trip',
  navHow: '使用方式',
  navFeatures: '功能',
  navMarketplace: '行程市集',
  navProduct: '產品',
  navResources: '資源',
  navSupport: '支援',
  navPrivacy: '隱私權政策',
  navTerms: '使用條款',
  external: '（外部連結）',
  login: '登入',
  start: '免費開始',
  downloadApp: '下載 KK Trip',
  downloadAppTitle: '用 KK Trip 規劃你的下一趟旅行',
  downloadAppBody: 'AI 幫你排行程、整理預訂，與旅伴一起規劃。',
  rss: '訂閱 RSS',
  readFull: '閱讀全文',
  allTopics: '全部',
  toc: '本文目錄',
  related: '延伸閱讀',
  copyLink: '複製連結',
  shareThis: '分享這篇文章',
  publishedOn: (date: string) => `發佈於 ${date}`,
  inTopic: '分類',
  copied: '已複製',
  footerBlurb: '旅行靈感、目的地指南與產品消息。',
  explore: '探索',
  topicsHeading: '主題',
  byline: '文章',
}
